# Generated by Django 4.1 on 2023-05-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_comment_approved_comment_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="approved_comment",
            field=models.BooleanField(default=False),
        ),
    ]
